services:
  app:
    build: .
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Los_Angeles
      - CRON_SCHEDULE=* * * * *
      - COMMAND=echo "Hello"
      - SCRIPT=test.sh
    volumes:
      - ./scripts:/app/scripts
